import dayjs from "dayjs";
import Link from "next/link";

export default function TermsOfServicePage() {
  const data = {
    product_name: "Clausia",
    last_updated: "2025-08-08",
    introduction: `These Terms of Service ("Terms") govern your access to and use of Clausia ("we", "us", "our"), a web-based AI tool that helps users generate privacy policies and related legal documents. By accessing or using Clausia you agree to these Terms and our Privacy Policy. If you do not agree, do not use the Service.`,
    section_titles: [
      "1. Contact Information",
      "2. Acceptance of Terms",
      "3. Eligibility",
      "4. Accounts and Access",
      "5. Account Sharing & Responsibility",
      "6. Acceptable Use & Prohibited Activities",
      "7. Ownership & Generated Content",
      "8. Payments, Credits & No Refunds",
      "9. Third-Party Services and Downtime",
      "10. Disclaimers and No Legal Advice",
      "11. Limitation of Liability",
      "12. Termination and Suspension",
      "13. Changes to the Service and Terms",
      "14. Governing Law and Dispute Resolution",
      "15. Miscellaneous"
    ],
    section_bodies: [
      `If you have any questions about these Terms or need assistance, contact us at:
Email: support@clausia.app`,

      `By accessing or using Clausia you confirm that you have read, understood, and agree to be bound by these Terms and our Privacy Policy. If you do not agree with any part of these Terms, you must stop using the Service immediately.`,

      `Clausia is intended for users aged 13 and older. You represent and warrant that you are at least 13 years old and have the legal capacity to enter into binding contracts in your jurisdiction. If you are using Clausia on behalf of an entity, you represent that you have the authority to bind that entity to these Terms.`,

      `An account is required to use the Service. Accounts are created using Google or GitHub sign-in. You agree to provide accurate information when creating an account and to keep your account credentials secure. You are responsible for all activity that occurs under your account.`,

      `You may share access to your Clausia account by sharing your linked Google or GitHub credentials, but doing so is at your own risk. Shared accounts remain your responsibility — you are liable for actions taken by anyone using your account. If you suspect unauthorized access, you must notify support@clausia.app immediately.`,

      `You agree not to use Clausia for any unlawful purpose or in any manner that could harm, disable, overburden, or impair the Service. Prohibited activities include, but are not limited to:
- Reverse-engineering, decompiling, or attempting to extract source code or proprietary logic.
- Using the Service to create, generate, or distribute content that is illegal, infringing, hateful, harassing, or otherwise violates third-party rights.
- Attempting to disrupt the Service or bypass usage limits.
We reserve the right to suspend or terminate accounts that engage in prohibited activities or otherwise threaten the integrity of the Service.`,

      `All rights, title and interest in the Clausia platform, software, user interface, and underlying systems belong to Clausia. You retain ownership of any policies or documents you generate using Clausia. You may share, distribute, or sell generated policies; however, if you publish a live policy via Clausia, the live link will be hosted under the clausia.app domain unless you arrange white-labeling with us. "Reuse" in this context means Clausia will not claim ownership of the textual output you generate for your use; Clausia will not republish or commercialize your generated content except as required to provide the Service (for example, hosting live links under clausia.app).`,

      `Clausia operates on a credit-based model. Credits are purchased as one-time credit packs through Razorpay. International payments are not accepted for paid purchases; international users can use free credits until they are exhausted. All sales are final — there are no refunds under any circumstances. If you have billing issues, contact support@clausia.app and we will investigate.`,

      `Clausia depends on third-party service providers for certain functionality, including but not limited to:
- OpenAI (to process your inputs and generate document drafts),
- Supabase (authentication and data storage),
- Razorpay (payment processing),
- Vercel (hosting and analytics).
You agree that your use of the Service may be subject to those providers' terms and privacy practices. We are not liable for failures, downtime, degraded performance, or data handling by these third parties.`,

      `THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE". CLAUSIA DOES NOT PROVIDE LEGAL ADVICE. DOCUMENTS GENERATED BY CLAUSIA ARE TEMPLATES AND SUGGESTED DRAFTS ONLY. YOU MUST REVIEW, ADAPT, AND, IF NECESSARY, SEEK INDEPENDENT LEGAL ADVICE BEFORE RELYING ON ANY GENERATED DOCUMENT. CLAUSIA MAKES NO WARRANTIES THAT ANY GENERATED DOCUMENT IS COMPLETE, ACCURATE, OR COMPLIANT WITH APPLICABLE LAWS.`,

      `TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, CLAUSIA'S TOTAL AGGREGATE LIABILITY ARISING OUT OF OR RELATED TO THESE TERMS OR YOUR USE OF THE SERVICE SHALL BE LIMITED TO THE AMOUNTS ACTUALLY PAID BY YOU TO CLAUSIA IN THE TWELVE (12) MONTHS PRIOR TO THE EVENT GIVING RISE TO LIABILITY. IN NO EVENT WILL CLAUSIA BE LIABLE FOR ANY INDIRECT, INCIDENTAL, CONSEQUENTIAL, SPECIAL, OR PUNITIVE DAMAGES, OR LOSS OF PROFITS, REVENUE, DATA, OR BUSINESS OPPORTUNITY.`,

      `We may suspend or terminate your access (or a portion of the Service) immediately if you breach these Terms, engage in prohibited activity, or for other legitimate reasons such as security incidents. Upon termination, your right to use the Service will end and Clausia may delete or disable access to your account and generated content in accordance with our Privacy Policy.`,

      `We may update these Terms from time to time. When we do, we will update the "Last updated" date on this page. Continued use of the Service after changes constitutes acceptance of the revised Terms. For material changes, we may provide additional notice such as an in-app banner or email to account holders, but we are not required to do so beyond updating the date.`,

      `These Terms are governed by the laws of India. You and Clausia agree to submit to the exclusive jurisdiction of the courts located in India for any dispute arising out of or relating to these Terms, to the extent permitted by law.`,

      `These Terms constitute the entire agreement between you and Clausia regarding the Service and supersede all prior agreements. If any provision of these Terms is found to be invalid or unenforceable, the remaining provisions will remain in full force and effect. Clausia may assign or transfer its rights and obligations under these Terms without restriction; you may not assign your rights under these Terms without our prior written consent.`
    ]
  };

  return (
    <>
      {/* Navbar */}
      <nav className="w-full px-6 md:px-12 py-4 border-b border-slate-200 flex justify-between items-center">
        <Link
          href="/"
          className="text-2xl font-bold bg-gradient-to-r from-purple-600 to-pink-600 bg-clip-text text-transparent"
          style={{ fontFamily: "chillax" }}
        >
          Clausia
        </Link>
        <a
          href="mailto:support@clausia.app"
          className="group px-6 py-2.5 rounded-full bg-gradient-to-r from-purple-600 to-pink-600 text-white font-medium text-sm hover:shadow-lg hover:scale-105 transition-all duration-200 flex items-center gap-2"
        >
          Contact Us
        </a>
      </nav>

      {/* Main Content */}
      <div className="px-6 md:px-12 py-16 max-w-4xl mx-auto">
        <div className="mb-16">
          <h1 className="text-5xl font-extrabold tracking-tight text-black mb-4">Terms of Service</h1>
          <p className="text-sm text-slate-500">Last updated on {dayjs(data.last_updated).format("MMMM D, YYYY")}</p>
        </div>

        <div className="mb-12">
          <p className="text-lg text-slate-700 leading-relaxed">
            These Terms of Service (&quot;Terms&quot;) govern your access to and use of <span className="font-semibold text-black">{data.product_name}</span>. By using our service, you agree to these Terms and our Privacy Policy.
          </p>
        </div>

        <section className="mb-16">
          <h2 className="text-2xl font-semibold text-black mb-4">Introduction</h2>
          <p className="text-base text-slate-800 leading-relaxed whitespace-pre-line">
            {data.introduction}
          </p>
        </section>

        {data.section_titles?.map((title, idx) => (
          <section key={idx} className="mb-16 border-l-4 border-purple-600 pl-6 transition-all duration-300 ease-in-out">
            <h2 className="text-2xl font-semibold text-black mb-3">{title}</h2>
            <p className="text-base text-slate-800 leading-relaxed whitespace-pre-line">
              {data.section_bodies?.[idx]}
            </p>
          </section>
        ))}
      </div>

      <footer className="py-16 px-6 bg-slate-900 text-white">
        <div className="max-w-7xl mx-auto">
          <div className="grid md:grid-cols-4 gap-12">
            <div className="md:col-span-2">
              <h4
                className="text-2xl font-bold bg-gradient-to-r from-purple-400 to-pink-400 bg-clip-text text-transparent mb-4"
                style={{ fontFamily: "chillax" }}
              >
                Clausia
              </h4>
              <p className="text-slate-400 mb-6 max-w-md leading-relaxed">
                The fastest way for Indian developers to generate professional,
                compliant privacy policies. Built by developers, for developers.
              </p>
              <div className="space-y-2">
                <p className="text-slate-400">
                  Support:{" "}
                  <a
                    href="mailto:support@clausia.app"
                    className="text-purple-400 hover:text-purple-300 transition-colors"
                  >
                    support@clausia.app
                  </a>
                </p>
              </div>
            </div>

            <div>
              <h5 className="font-semibold mb-4 text-white">Legal</h5>
              <ul className="space-y-3 text-slate-400">
                <li>
                  <a href="/legal/privacypolicy" className="hover:text-white transition-colors">
                    Privacy Policy
                  </a>
                </li>
                <li>
                  <a href="/legal/termsofservice" className="hover:text-white transition-colors">
                    Terms of Service
                  </a>
                </li>
              </ul>
            </div>
          </div>

          <div className="border-t border-slate-800 mt-12 pt-8 text-center">
            <p className="text-slate-400">© 2025 Clausia. Made with ❤️ for Indian developers.</p>
          </div>
        </div>
      </footer>
    </>
  );
}
